### PR TITLE
Corss build for scala 2.12

### PR DESCRIPTION
**Pull request by bambuchaAdm**
Use `wiremock-jre8` and remove overrides in dependencies

### CODE REVIEW

**Review by konradwudkowski — CHANGES_REQUESTED** [review]
Hi @bambuchaAdm, thanks for another contribution! 

We need to bump major version because of play auditing, can you please amend the commit and in the message include information why major was bumped, this will end up in release notes and will help teams understand the change. There's also that usual spelling error with `corss`... Thanks!

**Comment by bambuchaAdm** [comment]
Are we sure about bumping to `1.x` line. According to [sem-ver] line `0.x` has no guarantees about compatibility. 

[sem-ver]: https://semver.org/#spec-item-4

**Comment by bambuchaAdm** [comment]
According to [github search](https://github.com/search?q=org%3Ahmrc+auditFromPlayFrontend&type=Code) update in audit should cause not damage to services.

**Comment by konradwudkowski** [comment]
Hi @bambuchaAdm you're right, let's keep 0.x until play 2.6 is no longer a trial

**Pull request merged**
